name: MagicCardPro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141011'
    - '#e3eff7'
    - '#065781'
    - '#84c5e5'
    - '#a32f17'
  brandStrength: 0.10771372262388468
  lightness: 0.377209085971117
  saturation: 0.5556703258771449
  rhythmicContrast: 0.7545829701703042
purpose: []
